sudo: false
language: scala
scala: 2.13.10
jdk: oraclejdk17
dist: trusty

notifications:
  email: false
env:
  global: TERM=dumb

install: ./gradlew setupCIWorkspace
script: ./gradlew build

cache:
  directories:
  - $HOME/.gradle/caches
